# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

orthoL2Equidense <- function(X, tGrid) {
    .Call('_BTSinFLRM_orthoL2Equidense', PACKAGE = 'BTSinFLRM', X, tGrid)
}

#' @export
Xsim <- function(n, ev, ef, xi_type = 1L, nu_xi = 1) {
    .Call('_BTSinFLRM_Xsim', PACKAGE = 'BTSinFLRM', n, ev, ef, xi_type, nu_xi)
}

#' @export
Ysim <- function(X, beta, ev, ef, tGrid, distn_type = 1L, var_type = 1L, dep_type = 1L) {
    .Call('_BTSinFLRM_Ysim', PACKAGE = 'BTSinFLRM', X, beta, ev, ef, tGrid, distn_type, var_type, dep_type)
}

inferFLRM <- function(X, Y, X0, tGrid, kn_vec, hn_vec, gn_vec, ap = 0.05) {
    .Call('_BTSinFLRM_inferFLRM', PACKAGE = 'BTSinFLRM', X, Y, X0, tGrid, kn_vec, hn_vec, gn_vec, ap)
}

RBinner <- function(idx, X, Y, X0, tGrid, betaHat_mat, Y0Hat_mat, Y0Hat_trunc_hg_cube, erHatCent_mat, YHat_mat, XCent, YTilde_mat, Y0Tilde_mat, GaInvHat_cube, txHat_mat_h, kn_vec, hn_vec, gn_vec) {
    .Call('_BTSinFLRM_RBinner', PACKAGE = 'BTSinFLRM', idx, X, Y, X0, tGrid, betaHat_mat, Y0Hat_mat, Y0Hat_trunc_hg_cube, erHatCent_mat, YHat_mat, XCent, YTilde_mat, Y0Tilde_mat, GaInvHat_cube, txHat_mat_h, kn_vec, hn_vec, gn_vec)
}

RBouter <- function(X, Y, X0, tGrid, betaHat_mat, Y0Hat_mat, Y0Hat_trunc_hg_cube, erHatCent_mat, YHat_mat, XCent, YTilde_mat, Y0Tilde_mat, GaInvHat_cube, txHat_mat_h, stat_nonstd_mat, stat_Tstd_mat, kn_vec, hn_vec, gn_vec, M_bts, ap = 0.05) {
    .Call('_BTSinFLRM_RBouter', PACKAGE = 'BTSinFLRM', X, Y, X0, tGrid, betaHat_mat, Y0Hat_mat, Y0Hat_trunc_hg_cube, erHatCent_mat, YHat_mat, XCent, YTilde_mat, Y0Tilde_mat, GaInvHat_cube, txHat_mat_h, stat_nonstd_mat, stat_Tstd_mat, kn_vec, hn_vec, gn_vec, M_bts, ap)
}

PBinner1 <- function(idx, X, Y, X0, tGrid, betaHat_mat, UHat_mat, sxHat_cube_kh, Y0Hat_mat, Y0Hat_trunc_hg_cube, kn_vec, hn_vec, gn_vec) {
    .Call('_BTSinFLRM_PBinner1', PACKAGE = 'BTSinFLRM', idx, X, Y, X0, tGrid, betaHat_mat, UHat_mat, sxHat_cube_kh, Y0Hat_mat, Y0Hat_trunc_hg_cube, kn_vec, hn_vec, gn_vec)
}

PBinner2 <- function(idxTilde, X, YTilde_mat, X0, tGrid, betaTilde_mat, UTilde_mat, sxHat_cube_kh, Y0Tilde_mat, kn_vec, hn_vec, gn_vec) {
    .Call('_BTSinFLRM_PBinner2', PACKAGE = 'BTSinFLRM', idxTilde, X, YTilde_mat, X0, tGrid, betaTilde_mat, UTilde_mat, sxHat_cube_kh, Y0Tilde_mat, kn_vec, hn_vec, gn_vec)
}

PBouter <- function(X, Y, X0, tGrid, betaHat_mat, UHat_mat, sxHat_cube_kh, Y0Hat_mat, Y0Hat_trunc_hg_cube, YTilde_mat, betaTilde_mat, UTilde_mat, Y0Tilde_mat, stat_nonstd_mat, stat_Sstd_cube_kh, kn_vec, hn_vec, gn_vec, M_bts, ap = 0.05) {
    .Call('_BTSinFLRM_PBouter', PACKAGE = 'BTSinFLRM', X, Y, X0, tGrid, betaHat_mat, UHat_mat, sxHat_cube_kh, Y0Hat_mat, Y0Hat_trunc_hg_cube, YTilde_mat, betaTilde_mat, UTilde_mat, Y0Tilde_mat, stat_nonstd_mat, stat_Sstd_cube_kh, kn_vec, hn_vec, gn_vec, M_bts, ap)
}

WBinner <- function(W, X, Y, X0, tGrid, betaHat_mat, Y0Hat_mat, Y0Hat_trunc_hg_cube, erHat_mat, YHat_mat, XCent, YTilde_mat, Y0Tilde_mat, GaInvHat_cube, sxHat_cube_kh, kn_vec, hn_vec, gn_vec) {
    .Call('_BTSinFLRM_WBinner', PACKAGE = 'BTSinFLRM', W, X, Y, X0, tGrid, betaHat_mat, Y0Hat_mat, Y0Hat_trunc_hg_cube, erHat_mat, YHat_mat, XCent, YTilde_mat, Y0Tilde_mat, GaInvHat_cube, sxHat_cube_kh, kn_vec, hn_vec, gn_vec)
}

WBouter <- function(X, Y, X0, tGrid, betaHat_mat, Y0Hat_mat, Y0Hat_trunc_hg_cube, erHat_mat, YHat_mat, XCent, YTilde_mat, Y0Tilde_mat, GaInvHat_cube, sxHat_cube_kh, stat_nonstd_mat, stat_Sstd_cube_kh, kn_vec, hn_vec, gn_vec, W, ap = 0.05) {
    .Call('_BTSinFLRM_WBouter', PACKAGE = 'BTSinFLRM', X, Y, X0, tGrid, betaHat_mat, Y0Hat_mat, Y0Hat_trunc_hg_cube, erHat_mat, YHat_mat, XCent, YTilde_mat, Y0Tilde_mat, GaInvHat_cube, sxHat_cube_kh, stat_nonstd_mat, stat_Sstd_cube_kh, kn_vec, hn_vec, gn_vec, W, ap)
}

